<?php use_layout(':user/layout') ?>
<?php start_block('user_content') ?>
<h1><?= text('user', 'settings') ?></h1>
<?php if ($userSession->hasFlash('settings_messages')): ?>
    <div class="info-box">
        <ul>
            <?php foreach ($userSession->getFlash('settings_messages') as $message): ?>
                <li><?= $message ?></li>
            <?php endforeach ?>
        </ul>
    </div>
<?php endif ?>
<form action="<?= route_url('settings') ?>" method="post">
    <?= $form->fetch() ?>
    <div class="form-row">
        <input type="submit" value="<?= text('user', 'save_settings') ?>">
    </div>
</form>
<?php end_block() ?>